### PR TITLE
Increase the registry's group attribute description.

### PR DESCRIPTION
**Pull request by ningyu1**
## What is the purpose of the change

Optimize the document. #144

## Brief changelog

Increase the registry's group attribute description.  md files #145 
Compiled HTML and json files.

Follow this checklist to help us incorporate your contribution quickly and easily:

- [x] Make sure there is a [GITHUB_issue](https://github.com/apache/incubator-dubbo-website/issues) filed for the change (usually before you start working on it). Trivial changes like typos do not require a GITHUB issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
- [ ] Format the pull request title like `Fix UnknownException when host config not exist #XXX`. Each commit in the pull request should have a meaningful subject line and body.
- [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [ ] Test your code locally by running `docsite start`, and make sure it works as expected.
- [ ] Make sure no files under build directory is added.
- [ ] If this contribution is large, please follow the [Software Donation Guide](https://github.com/apache/incubator-dubbo/wiki/Software-donation-guide).

### CODE REVIEW

**Comment by carryxyh** [comment]
LGTM

**Comment by diecui1202** [comment]
Why do not have the source .md file changed?

**Comment by diecui1202** [comment]
@ningyu1 It's recommended that just push the .md files. maybe [The README.md](https://github.com/apache/incubator-dubbo-website/blob/asf-site/README.md) can help you.

**Comment by carryxyh** [comment]
Hi, @diecui1202 
This is the related pr which change the md: https://github.com/apache/incubator-dubbo-website/pull/145 
Currently this pr is a commit after build.

**Comment by diecui1202** [comment]
@ningyu1 Got it.

It's not a good way to file a PR with the build result. It'll conflict when there have more then 2 PRs. 

So I suggest build it manually, the one who merge the PR will be responsible to build the site, and push the changes direct to `asf-site` branch.

**Comment by carryxyh** [comment]
Ok, I will pay attention to this problem next time.

**Comment by ningyu1** [comment]
@diecui1202 Okay, next time,Thanks for reminding me

**Pull request merged**
