### PR TITLE
Add an article about how to update dubbo information on apache official site

### PR DESCRIPTION
**Pull request by tswstarplanet**
## What is the purpose of the change

XXXXX

## Brief changelog

XXXXX

Follow this checklist to help us incorporate your contribution quickly and easily:

- [x] Make sure there is a [GITHUB_issue](https://github.com/apache/incubator-dubbo-website/issues) filed for the change (usually before you start working on it). Trivial changes like typos do not require a GITHUB issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
- [ ] Format the pull request title like `Fix UnknownException when host config not exist #XXX`. Each commit in the pull request should have a meaningful subject line and body.
- [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [ ] Test your code locally by running `docsite start`, and make sure it works as expected.
- [ ] Make sure no files under build directory is added.
- [ ] If this contribution is large, please follow the [Software Donation Guide](https://github.com/apache/incubator-dubbo/wiki/Software-donation-guide).

### CODE REVIEW

**Comment by tswstarplanet** [comment]
I see the README say that building the website requires docsite 1.3.3 . But I find the latest release of docsite is 1.2.3.
Does the README make a mistake ?

**Comment by ralf0131** [comment]
> I see the README say that building the website requires docsite 1.3.3 . But I find the latest release of docsite is 1.2.3.
> Does the README make a mistake ?

The latest version is 1.3.8. https://www.npmjs.com/package/docsite

**Comment by tswstarplanet** [comment]
I tried to install docsite, but it fails. So I don't know if the website can run correctly after my modification of the developer.js .

**Comment by ralf0131** [comment]
Please paste your error message.

**Comment by tswstarplanet** [comment]
I modify the develop.js. 
I use node 8.15.0 to install docsite 1.3.8, and use docsite to build the site. It generate the corresponding html and json of the .md file. 
But when I start the server and access by the explorer. The sidebar doesn't show the title of the article.

**Comment by tswstarplanet** [comment]
Everything is ok and I have updated the develop.js .

**Comment by ralf0131** [comment]
Hi, sorry but would you please resolve the conflict first?

**Pull request merged**
