### PR TITLE
对dubbo的spi作了一点补充

### PR DESCRIPTION
**Pull request by huyuechy**

### CODE REVIEW

**Comment by huyuechy** [comment]
Sorry,I cannot find the English documentation about dubbo spi .Where can I add the English documentation?

**Comment by ralf0131** [comment]
Yes, there is not for the moment, but if you could contribute to that which will be much appreciated.

For other documentation, we encourage each pull request to be both Chinese and English :)

I will merge it anyway.

**Comment by ralf0131** [comment]
Oh I forgot one thing, you need to send the generated static html file as well. Otherwise it won't take effect.

Please refer to the build instructions: https://github.com/apache/incubator-dubbo-website/blob/asf-site/README.md

This is not very convenient, but we have to do this.

**Comment by huyuechy** [comment]
ok,I will do it as soon as possible

**Pull request merged**
