### PR TITLE
Translate Design Principals part1 #196

### PR DESCRIPTION
**Pull request by biyuhao**
## What is the purpose of the change

Add english version of http://dubbo.apache.org/zh-cn/docs/dev/principals

## Brief changelog

It's still a work in progress. I will continuously push to this branch.

- [x] code-detail.md
- [ ] configuration.md
- [x] dummy.md
- [ ] expansibility.md
- [ ] extension.md
- [ ] general-knowledge.md
- [x] introduction.md
- [ ] robustness.md

Follow this checklist to help us incorporate your contribution quickly and easily:

- [x] Make sure there is a [GITHUB_issue](https://github.com/apache/incubator-dubbo-website/issues) filed for the change (usually before you start working on it). Trivial changes like typos do not require a GITHUB issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
- [ ] Format the pull request title like `Fix UnknownException when host config not exist #XXX`. Each commit in the pull request should have a meaningful subject line and body.
- [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [ ] Test your code locally by running `docsite start`, and make sure it works as expected.
- [ ] Make sure no files under build directory is added.
- [ ] If this contribution is large, please follow the [Software Donation Guide](https://github.com/apache/incubator-dubbo/wiki/Software-donation-guide).

### CODE REVIEW

**Comment by kezhenxu94** [comment]
> I found that several articles were not translated into English. Was this submission wrong?I think if there is no translation here, it is better to leave it blank. What do you think?

@lixiaojiee This pull request is still in progress and not yet finished, see the comment that the author left, the file you reviewed **dummy.md** is not yet translated:

> It's still a work in progress. I will continuously push to this branch.
> 
> * [x]  code-detail.md
> * [ ]  configuration.md
> * [ ]  dummy.md
> * [ ]  expansibility.md
> * [ ]  extension.md
> * [ ]  general-knowledge.md
> * [x]  introduction.md
> * [ ]  robustness.md

**Comment by lixiaojiee** [comment]
I am very that I did not see the comment before,the pr can be left on, I can add a label.

**Comment by kezhenxu94** [comment]
> I am sorry that I did not see the comment before,the pr can be left on, I can add a label.

I don't think the tag(`will merge later`) is necessary, because it is a draft PR and cannot be merged, and the title of the PR(**WIP**) indicates that this work is **Working In Progress**, so I think if the tag is really needed, it should be call **WIP** or **work in progress**
image

**Comment by lixiaojiee** [comment]
> > I am sorry that I did not see the comment before,the pr can be left on, I can add a label.
> 
> I don't think the tag(`will merge later`) is necessary, because it is a draft PR and cannot be merged, and the title of the PR(**WIP**) indicates that this work is **Working In Progress**, so I think if the tag is really needed, it should be called **WIP** or **work in progress**
> image

I get it，thank you

**Comment by caojiele** [comment]
@biyuhao I've done [here](https://github.com/apache/incubator-dubbo-website/pull/310), this can be closed.

**Comment by biyuhao** [comment]
@caojiele ok, let's separate this work into these two PRs for review.

**Comment by caojiele** [comment]
> @caojiele ok, let's separate this work into these two PRs for review.

Alright.

**Pull request merged**
