### PR TITLE
Add release guide blog to developers page

### PR DESCRIPTION
**Pull request by caojiele**
## What is the purpose of the change
Add release guide blog to developers page #296 

## Brief changelog
docs/zh-cn/developers/committer-guide/release-guide_dev.md
docs/en-us/developers/committer-guide/release-guide_dev.md

Follow this checklist to help us incorporate your contribution quickly and easily:

* [x]  Make sure there is a [GITHUB_issue](https://github.com/apache/incubator-dubbo-website/issues) filed for the change (usually before you start working on it). Trivial changes like typos do not require a GITHUB issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
* [ ]  Format the pull request title like `Fix UnknownException when host config not exist #XXX`. Each commit in the pull request should have a meaningful subject line and body.
* [ ]  Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
* [ ]  Test your code locally by running `docsite start`, and make sure it works as expected.
* [ ]  Make sure no files under build directory is added.
* [ ]  If this contribution is large, please follow the [Software Donation Guide](https://github.com/apache/incubator-dubbo/wiki/Software-donation-guide).

### CODE REVIEW

**Comment by ralf0131** [comment]
Please also do not mix the pull request. You should separate it in to 2 pull request.

**Comment by caojiele** [comment]
> Please also do not mix the pull request. You should separate it in to 2 pull request.

OK, Let me change.

**Comment by caojiele** [comment]
> It seems that you have submitted some redundant files, such as .json and.html, which will be generated automatically, you just need to submit the .md file to the correct directory

Before I was changed some redundant files, behind all changed back, now only changed. Md files

**Comment by lixiaojiee** [comment]
> > It seems that you have submitted some redundant files, such as .json and.html, which will be generated automatically, you just need to submit the .md file to the correct directory
> 
> Before I was changed some redundant files, behind all changed back, now only changed. Md files

These files appear to have changed line breaks

**Comment by caojiele** [comment]
> > > It seems that you have submitted some redundant files, such as .json and.html, which will be generated automatically, you just need to submit the .md file to the correct directory
> > 
> > 
> > Before I was changed some redundant files, behind all changed back, now only changed. Md files
> 
> These files appear to have changed line breaks

Yes, more than one line, but the line can't delete, I don't know what is the version number before.

**Pull request closed without merging**
