### PR TITLE
 Modify the description of the config of the property of protocol so t…  … …hat the document is consistent with the code

### PR DESCRIPTION
**Pull request by tswstarplanet**
## What is the purpose of the change

XXXXX

## Brief changelog

XXXXX

Follow this checklist to help us incorporate your contribution quickly and easily:

- [x] Make sure there is a [GITHUB_issue](https://github.com/apache/incubator-dubbo-website/issues) filed for the change (usually before you start working on it). Trivial changes like typos do not require a GITHUB issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
- [ ] Format the pull request title like `Fix UnknownException when host config not exist #XXX`. Each commit in the pull request should have a meaningful subject line and body.
- [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [ ] Test your code locally by running `docsite start`, and make sure it works as expected.
- [ ] Make sure no files under build directory is added.
- [ ] If this contribution is large, please follow the [Software Donation Guide](https://github.com/apache/incubator-dubbo/wiki/Software-donation-guide).

### CODE REVIEW

**Comment by ralf0131** [comment]
Hi, please also update the English version as well.

**Comment by tswstarplanet** [comment]
@ralf0131 OK, I just forgotten this, I will do it this night.

**Comment by tswstarplanet** [comment]
I have updated the English version document

**Comment by ralf0131** [comment]
LGTM, thanks for the pull request!

**Pull request merged**
