### PR TITLE
Add blog post for Sentinel (CN)

### PR DESCRIPTION
**Pull request by sczyh30**
Add blog post for Sentinel (in Chinese).
cc @jialianglinjl

The English version is still on the way. Once it's finished, I'll create another PR.

### CODE REVIEW

**Comment by ralf0131** [comment]
Hi, 

Thanks for the pull request, please do not upload the files under build/ directory. 

Please refer to check list in the pull request template.

**Comment by ralf0131** [comment]
One more question: why md_json/docs.json need to be updated?

**Comment by sczyh30** [comment]
It seems no actual change in `md_json/docs.json`. I've fixed that and removed build files.

**Comment by ralf0131** [comment]
LGTM, thanks for the pr!

**Pull request merged**
