### PR TITLE
[Dubbo-Website-314] Add report doc issue and edit doc links

### LINKED ISSUE #314: 文档-建议
建议: 在每篇文档的底部加上链接, "发现错误？想参与编辑？ 在 GitHub 上编辑此页！" ,dubbo越来越好,离不开一点点的进步.

### PR DESCRIPTION
**Pull request by kezhenxu94**
## What is the purpose of the change

resolve #314

## Brief changelog

XXXXX

Follow this checklist to help us incorporate your contribution quickly and easily:

- [x] Make sure there is a [GITHUB_issue](https://github.com/apache/incubator-dubbo-website/issues) filed for the change (usually before you start working on it). Trivial changes like typos do not require a GITHUB issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
- [ ] Format the pull request title like `Fix UnknownException when host config not exist #XXX`. Each commit in the pull request should have a meaningful subject line and body.
- [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [ ] Test your code locally by running `docsite start`, and make sure it works as expected.
- [ ] Make sure no files under build directory is added.
- [ ] If this contribution is large, please follow the [Software Donation Guide](https://github.com/apache/incubator-dubbo/wiki/Software-donation-guide).

### CODE REVIEW

**Comment by kezhenxu94** [comment]
works like this:

image

**Comment by xixifeng** [comment]
@kezhenxu94 
It would be better if you could locate a specific edit page instead of a wide entrance.

**Comment by kezhenxu94** [comment]
> @kezhenxu94
> It would be better if you could locate a specific edit page instead of a wide entrance.

Yes I agree with you, but the links are now added in the footer, which is globally effective, maybe we can improve this to make it link to specific page in the future, but for now it is better than when it was not added

**Comment by htynkn** [comment]
> > @kezhenxu94
> > It would be better if you could locate a specific edit page instead of a wide entrance.
> 
> Yes I agree with you, but the links are now added in the footer, which is globally effective, maybe we can improve this to make it link to specific page in the future, but for now it is better than before when it was not added

I agree to have specific edit page. not sure if docsite support this feature.

**Comment by kezhenxu94** [comment]
> > > @kezhenxu94
> > > It would be better if you could locate a specific edit page instead of a wide entrance.
> > 
> > 
> > Yes I agree with you, but the links are now added in the footer, which is globally effective, maybe we can improve this to make it link to specific page in the future, but for now it is better than before when it was not added
> 
> I agree to have specific edit page. not sure if docsite support this feature.

Since users have to fork and send PR's, I think linking to the home page of the project at GitHub is acceptable for now, though others can try to find out whether docsite support it or not.

**Comment by htynkn** [comment]
https://github.com/txd-team/docsite/issues/23

**Pull request merged**
